---
platform: linux

#inputs:
# - name: image

params:
 ASDK_VERSION: 1910
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
#outputs:
#  - name: asdk-release
run:
  path: bash
  args:
  - "-c"
  - |
    set -eu
    ls -lisaR .
    pwd