---
platform: linux

params:
 ASDK_VERSION: 1910
 FROM: 00
 TO: 100
outputs:
  - name: asdk-release
run:
  path: bash
  args:
  - "-c"
  - |
    set -e
    for i in {$FROM..$TO}
      do
        url="https://azurestack.azureedge.net/asdk${ASDK_VERSION}-${i}/AzureStackDevelopmentKit.exe"
        if curl --output /dev/null --silent --head --fail "$url"; then
            echo "URL exists: $url"
            RELEASE=https://azurestack.azureedge.net/asdk${ASDK_VERSION}-${i}
            break
        else
            echo "URL does not exist: $url"
        fi
      done
    if [[ -z "${RELEASE}" ]]
    then
      echo "No new Release found"
    else
      RELEASEFILE=asdk-release/asdk-${ASDK_VERSION}.${i}.yml
      echo "RELEASE: $ASDK_VERSION" >> ${RELEASEFILE}
      echo "BUILD: $i" >> ${RELEASEFILE}
      cat ${RELEASEFILE}
    fi
