---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: azs-concourse
outputs:


params:
  GOVC_INSECURE: 
  GOVC_PASSWORD: 
  GOVC_URL: 
  GOVC_USERNAME: Administrator@vsphere.local
  GOVC_VM:
  NVE_FQDN:
  NVE_TIMEZONE: "Europe/Berlin"
  NVE_ADMIN_PASSWORD_OS: "Password123!"
  NVE_ROOT_PASSWORD_OS: "Password123!"
  NVE_SNMP_STRING: public
  NVE_DATADOMAIN_HOST:
  NVE_STORAGE_PATH:
  NVE_DDBOOST_USER:
  NVE_DDBOOST_USER_PWD: 
  NVE_DDBOOST_USER_PWD_CF: 
  NVE_DATADOMAIN_SYSADMIN: 
  NVE_DATADOMAIN_SYSADMIN_PWD: 
  NVE_TOMCAT_KEYSTORE_PASSWORD: "Password123!"
  NVE_AUTHC_ADMIN_PASSWORD: "Password123!"
  

run:
  path: azs-concourse/ci/scripts/configure-nve.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml