---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: azs-concourse
outputs:


params:
    GOVC_INSECURE: ((GOVC.INSECURE))
    GOVC_PASSWORD: ((GOVC.PASSWORD))
    GOVC_URL: ((GOVC.URL))
    GOVC_USERNAME: ((GOVC.USERNAME))
    GOVC_RESOURCE_POOL: ((GOVC.RESOURCE_POOL))
    GOVC_DATASTORE: ((GOVC.DATASTORE)) 
    GOVC_DATACENTER: ((GOVC.DATACENTER)) 
    GOVC_NETWORK: ((GOVC.NETWORK))
    LABBUILDR_RESOURCE_POOL: ((LABBUILDR.LAB1.RESOURCE_POOL))
    LABBUILD_DATASTORE: ((LABBUILDR.LAB1.DATASTORE)) 
    LABBUILD_DATACENTER: ((LABBUILDR.LAB1.DATACENTER)
    LABBUILDR_NETWORK: ((LABBUILDR.LAB1.NETWORK))
    LABBUILDR_ADDRESS: ((LABBUILDR.LAB1.ADDRESS))
    LABBUILDR_GATEWAY: ((LABBUILDR.LAB1.GATEWAY))
    LABBUILDR_NETMASK: ((LABBUILDR.LAB1.NETMASK))
    LABBUILDR_FQDN: ((LABBUILDR.LAB1.FQDN))
    LABBUILDR_VMNAME: ((LABBUILDR.LAB1.VMNAME))
    LABBUILDR_DNS: ((LABBUILDR.LAB1.DNS)

run:
  path: azs-concourse/ci/scripts/configure-nve.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml