---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: azs-concourse
 - name: powerprotect
outputs:


params:
  GOVC_INSECURE: 
  GOVC_PASSWORD: 
  GOVC_URL: 
  GOVC_USERNAME: Administrator@vsphere.local
  GOVC_RESOURCE_POOL: 
  GOVC_DATASTORE: 
  GOVC_DATACENTER:   
  GOVC_NETWORK: 
  PPDM_NETWORK: 
  PPDM_ADDRESS: 
  PPDM_GATEWAY: 
  PPDM_NETMASK: 
  PPDM_FQDN: 
  PPDM_VMNAME:
  PPDM_DNS: 
  

run:
  path: azs-concourse/ci/scripts/deploy-ppdm.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml