---
platform: linux

inputs:
 - name: config # contains the env file with target OpsMan Information
 - name: azs-conourse


params:
  PROFILE: "2019-03-01-hybrid"
  CA_CERT: cert/root.pem
  ENDPOINT_RESOURCE_MANAGER: "https://management.local.azurestack.external"
  VAULT_DNS:  ".vault.local.azurestack.external"
  SUFFIX_STORAGE_ENDPOINT: "local.azurestack.external"
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
  AZURE_SUBSCRIPTION_ID:
  AZURE_CLI_CA_PATH: "/usr/local/lib/python3.6/site-packages/certifi/cacert.pem"
  DESTINATION_CONTAINER:
  DESTINATION_BLOB:
  ACCOUNT_NAME:

run:
  path: azs-concourse/ci/scripts/copy-status.sh