---
platform: linux

inputs:
 - name: config # contains the env file with target OpsMan Information


params:
  PROFILE: "2019-03-01-hybrid"
  CA_CERT: cert/root.pem
  ENDPOINT_RESOURCE_MANAGER: "https://management.local.azurestack.external"
  VAULT_DNS:  ".vault.local.azurestack.external"
  SUFFIX_STORAGE_ENDPOINT: "local.azurestack.external"
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
  AZURE_SUBSCRIPTION_ID:
  AZURE_CLI_CA_PATH: "/usr/local/lib/python3.6/site-packages/certifi/cacert.pem"
  DESTINATION_CONTAINER:
  DESTINATION_BLOB:
  ACCOUNT_NAME:

run:
  path: bash
  args:
  - "-c"
  - |
    set -eu
    az extension remove --name eventhub
    cat $(pwd)/config/${CA_CERT} >> ${AZURE_CLI_CA_PATH}
    az cloud register -n AzureStackUser \
    --endpoint-resource-manager ${ENDPOINT_RESOURCE_MANAGER} \
    --suffix-storage-endpoint ${SUFFIX_STORAGE_ENDPOINT} \
    --suffix-keyvault-dns ${VAULT_DNS}
    az cloud set -n AzureStackUser
    az cloud update --profile ${PROFILE}
    az cloud list --output table
    az login --service-principal \
     -u ${AZURE_CLIENT_ID} \
     -p ${AZURE_CLIENT_SECRET} \
     --tenant ${AZURE_TENANT_ID}
    set -eux
    az account set --subscription ${AZURE_SUBSCRIPTION_ID}
    until az storage blob show --account-name ${ACCOUNT_NAME} \
    --container-name ${DESTINATION_CONTAINER} \
    --name $DESTINATION_BLOB \
    --output json --query "[properties.copy.status=='success']" \
    2>/dev/null 
    do 
      echo "copy operation in progress, retrying in 60 seconds"
      sleep 60
    done
