---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: azs-concourse
 - name: kubeconfig
 - name: boshcli-product
 - name: ytt-product
 - name: kbld-product
 - name: kapp-product
 - name: tas-for-kubernetes-product
outputs:
 - name: cf-values
params:
  CF_CONFIG_FILE: cf-values-$timestamp.yml
  PROFILE: "2019-03-01-hybrid"
  CA_CERT: 
  ENDPOINT_RESOURCE_MANAGER: "https://management.local.azurestack.external"
  VAULT_DNS:  ".vault.local.azurestack.external"
  SUFFIX_STORAGE_ENDPOINT: "local.azurestack.external"
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
  AZURE_SUBSCRIPTION_ID:
  RESOURCE_GROUP:
  LOCATION:
  SYSTEM_DOMAIN:
  GCR_CRED:
  YTT_TAS_system_registry__hostname:
  YTT_TAS_system_registry__username:
  YTT_TAS_system_registry__password:
  YTT_TAS_app_registry__hostname:
  YTT_TAS_app_registry__repository: cf-workloads
  YTT_TAS_app_registry__username:
  YTT_TAS_app_registry__password:
  YTT_TAS_app_registry__ca:
run:
  path: azs-concourse/ci/scripts/deploy-tas-for-kubernetes-product.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml