---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: config
 - name: image
 - name: azs-conourse
params:
  PROFILE: "2019-03-01-hybrid"
  CA_CERT: cert/root.pem
  ENDPOINT_RESOURCE_MANAGER: "https://management.local.azurestack.external"
  VAULT_DNS:  ".vault.local.azurestack.external"
  SUFFIX_STORAGE_ENDPOINT: "local.azurestack.external"
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
  AZURE_SUBSCRIPTION_ID:
  AZURE_CLI_CA_PATH: "/usr/local/lib/python3.6/site-packages/certifi/cacert.pem"
  TEMPLATE_URI:
  OPSMAN_IMAGE_LOCATION: west_europe
  PARAMETER_FILE:
  RESOURCE_GROUP:
  LOCATION:
  ADDITIONAL_PARAMETERS: "{}"
  DESTINATION_CONTAINER: images
  ACCOUNT_NAME: 
  STATE_FILE: state.yml
  VM_NAME: ops_man_vm
  OPSMAN_URL: 
outputs:
- name: generated-state #contains the updated state file

run:
  path: azs-concourse/ci/scripts/delete-vm.sh