---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:

params:
  PROFILE: "2019-03-01-hybrid"
  CA_CERT: cert/root.pem
  ENDPOINT_RESOURCE_MANAGER: "https://management.local.azurestack.external"
  VAULT_DNS:  ".vault.local.azurestack.external"
  SUFFIX_STORAGE_ENDPOINT: "local.azurestack.external"
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
  AZURE_SUBSCRIPTION_ID:
  TEMPLATE_URI:
  PARAMETER_FILE:
  RESOURCE_GROUP:
  LOCATION:
  ADDITIONAL_PARAMETERS: "{}"

run:
  path: bash
  args:
  - "-c"
  - |
    set -eu
    echo "${CA_CERT}" >> ${AZURE_CLI_CA_PATH}
    az cloud register -n AzureStackUser \
    --endpoint-resource-manager ${ENDPOINT_RESOURCE_MANAGER} \
    --suffix-storage-endpoint ${SUFFIX_STORAGE_ENDPOINT} \
    --suffix-keyvault-dns ${VAULT_DNS} \
    --profile ${PROFILE}
    az cloud set -n AzureStackUser
    az cloud list --output table
    az login --service-principal \
     -u ${AZURE_CLIENT_ID} \
     -p ${AZURE_CLIENT_SECRET} \
     --tenant ${AZURE_TENANT_ID}
    set -eux 
    az account set --subscription ${AZURE_SUBSCRIPTION_ID}
    az group create --name ${RESOURCE_GROUP} --location ${LOCATION}
    az deployment group create \
    --mode incremental \
    --resource-group ${RESOURCE_GROUP} \
    --parameters config/${PARAMETER_FILE} \
    --parameters ${ADDITIONAL_PARAMETERS} \
    --template-uri ${TEMPLATE_URI} \
    --debug

