---
platform: linux

inputs:
 - name: asdk

# params:
# ASDK_VERSION: 1910
# FROM: 57
# TO: 58
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
outputs:
  - name: cloudbuilder
run:
  path: bash
  args:
  - "-c"
  - |
    set -e
    ls -lisaR .
    pwd
    cat asdk/url
    echo
    cat asdk/version
    IFS='.'
    read -r VERSION BUILD < ./asdk/version
    echo $VERSION
    echo $BUILD
