---
platform: linux

inputs:
 - name: asdk
 - name: azs-concourse

params:
  BASEURI: https://azurestackhub.azureedge.net/PR/download
  access_key_id: 
  endpoint:
  region_name:
  secret_access_key:
  bucket: 
outputs:
  - name: cloudbuilder
run:
  path: azs-concourse/ci/scripts/download-asdk.sh