---
platform: linux

inputs:
 - name: asdk

params:
  BASEURI: https://azurestack.azureedge.net/asdk
# ASDK_VERSION: 1910
# FROM: 57
# TO: 58
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
outputs:
  - name: cloudbuilder
run:
  path: bash
  args:
  - "-c"
  - |
    set -x
    ls -lisaR .
    pwd
    cat asdk/url
    echo
    cat asdk/version
    IFS='.'
    read -r ASDK_VERSION ASDK_BUILD <<< asdk/version
    echo $ASDK_VERSION
    echo $ASDK_BUILD
    URI="${BASEURI}/asdk${ASDK_VERSION}-${ASDK_BUILD}"
    echo "Downloading $URI/AzureStackDevelopmentKit.exe"
    curl "$URI/AzureStackDevelopmentKit.exe" --output cloudbuilder/AzureStackDevelopmentKit.exe
    file cloudbuilder/AzureStackDevelopmentKit.exe
