---
platform: linux

inputs:
 - name: azs-concourse

params:
  avamar: 
outputs:
  - name: AvamarUpgrade
  - name: UpgradeAvinstaller
  - name: UpgradeClientDownloads
  - name: UpgradeClientPluginCatalog 
  - name: ChangeNetworkSettings
run:
  path: azs-concourse/ci/scripts/download-avamar-upgrade.sh