---
platform: linux

inputs:
 - name: asdk

# params:
# ASDK_VERSION: 1910
# FROM: 57
# TO: 58
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
outputs:
  - name: cloudbuilder
run:
  path: bash
  args:
  - "-c"
  - |
    set -eu
    ls -lisaR .
    pwd
    cat asdk/url
    echo
    cat asdk/version
    printenv
    export ASDK_BUILD=$(\
        cat "./${PIPELINE}/vars/pivotal-container-service-vars.yml" | \
        grep -A 0 pks_api_hostname | \
        cut -d ':' -f2 | \
        tr -d ' "')  
