---
platform: linux

inputs:
 - name: asdk

params:
  BASEURI: https://azurestack.azureedge.net/asdk
  access_key_id: 
  endpoint:
  region_name:
  secret_access_key:
  bucket: 
# ASDK_VERSION: 1910
# FROM: 57
# TO: 58
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
outputs:
  - name: cloudbuilder
run:
  path: bash
  args:
  - "-c"
  - |
    set -x
    export AWS_SECRET_ACCESS_KEY=$secret_access_key
    export AWS_DEFAULT_REGION=$region_name
    export AWS_ACCESS_KEY_ID=$access_key_id
    IFS='.'
    read -r ASDK_VERSION ASDK_BUILD <<< $(cat asdk/version)
    echo $ASDK_VERSION
    echo $ASDK_BUILD
    unset IFS
    URI="${BASEURI}${ASDK_VERSION}-${ASDK_BUILD}"
    echo "Downloading $URI/AzureStackDevelopmentKit.exe"
    curl "$URI/AzureStackDevelopmentKit.exe" --output cloudbuilder/AzureStackDevelopmentKit.exe
    file cloudbuilder/AzureStackDevelopmentKit.exe

    # i=1
    # while curl "$URI/AzureStackDevelopmentKit-${i}.bin" --output "cloudbuilder/AzureStackDevelopmentKit-${i}.bin" 
    # do 
    #  file cloudbuilder/AzureStackDevelopmentKit-${i}.bin
    #  ((i++))
    # done
    aws --endpoint-url "${endpoint}" s3 cp ./cloudbuilder s3://${bucket}/${VERSION}-${BUILD} --recursive