---
platform: linux

inputs:
 - name: config # contains the env file with target OpsMan Information


params:
  PROFILE: "2019-03-01-hybrid"
  CA_CERT: cert/root.pem
  ENDPOINT_RESOURCE_MANAGER: "https://management.local.azurestack.external"
  VAULT_DNS:  ".vault.local.azurestack.external"
  SUFFIX_STORAGE_ENDPOINT: "local.azurestack.external"
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
  AZURE_SUBSCRIPTION_ID:
  DESTINATION_CONTAINER:
  DESTINATION_BLOB:
  SOURCE_URI:
  ACCOUNT_NAME:
  ACCOUNT_KEY:

run:
  path: bash
  args:
  - "-c"
  - |
    set -eu
    cat $(pwd)/config/${CA_CERT} >> ${AZURE_CLI_CA_PATH}
    az cloud register -n AzureStackUser \
    --endpoint-resource-manager ${ENDPOINT_RESOURCE_MANAGER} \
    --suffix-storage-endpoint ${SUFFIX_STORAGE_ENDPOINT} \
    --suffix-keyvault-dns ${VAULT_DNS} \
    --profile ${PROFILE}
    az cloud set -n AzureStackUser
    az cloud list --output table
    az login --service-principal \
     -u ${AZURE_CLIENT_ID} \
     -p ${AZURE_CLIENT_SECRET} \
     --tenant ${AZURE_TENANT_ID}
    set -eux 
    az account set --subscription ${AZURE_SUBSCRIPTION_ID}
    az storage blob incremental-copy start \
    --destination-blob ${DESTINATION_BLOB} \
    --destination-container ${DESTINATION_CONTAINER} \
    --source-uri ${SOURCE_URI} \
    --account-key ${ACCOUNT_KEY} \
    --account-name ${ACCOUNT_NAME}

