---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: azs-concourse
 - name: kubeconfig
# - name: kubectl-release

  

run:
  path: azs-concourse/ci/scripts/install-kubeapps.sh


# test with 
# echo "<preset variable yml>" > vars.yml
# while IFS=": " read -r field1 field2; do     export $field1=$field2; done < vars.yml