---
platform: linux

#inputs:
# - name: root_ca # contains the env file with target OpsMan Information

params:
  CA_CERT: 
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input

run:
  path: bash
  args:
  - "-c"
  - |
    find .
    ls -lisa
    pwd
    ls -lisa /
    # cat  root_ca/${CA_CERT}>> /tmp/root.cer
    # cat /tmp/root.cer
    # export REQUEST_CA_BUNDLE=/tmp/root.cer
    # export AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1 
    # export ADAL_PYTHON_SSL_NO_VERIFY=1
    # az cloud register -n AzureStackUser \
    #--endpoint-resource-manager "https://management.local.azurestack.external" \
    #--suffix-storage-endpoint "local.azurestack.external" \
    #--suffix-keyvault-dns ".vault.local.azurestack.external"
    #az cloud set -n AzureStackUser
    #az cloud update --profile 2019-03-01-hybrid
    #az cloud list --output table

