---
platform: linux

inputs:
 - name: image

params:
 OPSMAN_LOCATION: west_europe
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input

run:
  path: bash
  args:
  - "-c"
  - |
    ls -lisaR .
    pwd
    ls -lisa image/
    set
    grep -A0 "${OPSMAN_LOCATION}:" image/*.yml  | tail -n1 | awk '{ print $2 }'