---
platform: linux

#inputs:
#- name: env # contains the env file with target OpsMan Information

#params:
#  ENV_FILE: env.yml
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input

run:
  path: bash
  args:
  - "-c"
  - |
    set -eux
    echo "Azure Stack Automation for PCF"
    ls -lisa $HOME
    cat $HOME/.azure
    az 
    az extension add --name alias
    az alias remove --name eventhubs
    az extension list-available --output table
