---
# this simple tasksm get´s running vm´s of an azurestack subscription
platform: linux

inputs:
 - name: config
 - name: image

params:
  PROFILE: "2019-03-01-hybrid"
  CA_CERT: cert/root.pem
  ENDPOINT_RESOURCE_MANAGER: "https://management.local.azurestack.external"
  VAULT_DNS:  ".vault.local.azurestack.external"
  SUFFIX_STORAGE_ENDPOINT: "local.azurestack.external"
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
  AZURE_SUBSCRIPTION_ID:
  AZURE_CLI_CA_PATH: "/usr/local/lib/python3.6/site-packages/certifi/cacert.pem"
  TEMPLATE_URI:
  OPSMAN_IMAGE_LOCATION: west_europe
  PARAMETER_FILE:
  RESOURCE_GROUP:
  LOCATION:
  ADDITIONAL_PARAMETERS: "{}"
  DESTINATION_CONTAINER: images
  ACCOUNT_NAME: 
  STATE_FILE: state.yml
  VM_NAME: ops_man_vm
  RG_NAME: pcf
  OPSMAN_URL: 
outputs:
- name: generated-state #contains the updated state file

run:
  path: bash
  args:
  - "-c"
  - |
    set -eu
    cat $(pwd)/config/${CA_CERT} >> ${AZURE_CLI_CA_PATH}
    az cloud register -n AzureStackUser \
    --endpoint-resource-manager ${ENDPOINT_RESOURCE_MANAGER} \
    --suffix-storage-endpoint ${SUFFIX_STORAGE_ENDPOINT} \
    --suffix-keyvault-dns ${VAULT_DNS} \
    --profile ${PROFILE}
    az cloud set -n AzureStackUser
    az login --service-principal \
     -u ${AZURE_CLIENT_ID} \
     -p ${AZURE_CLIENT_SECRET} \
     --tenant ${AZURE_TENANT_ID}
    set -eux 
    az account set --subscription ${AZURE_SUBSCRIPTION_ID}
    SOURCE_URI=$(grep -A0 "${OPSMAN_IMAGE_LOCATION}:" image/*.yml  | tail -n1 | awk '{ print $2 }')
    OPSMAN_VHD=$(basename $SOURCE_URI)
    OPSMAN_CURRENT=$(curl ${OPSMAN_URL}/api/v0/info -s -X GET -k -H "Authorization: Bearer" | jp.py info.version | tr -d '"')
    OPSMAN_NEW=$(echo $OPSMAN_VHD | egrep -o '[0-9]+.*-build.[0-9]+')
    echo "Found ${OPSMAN_NEW}, have ${OPSMAN_CURRENT}"
    if [ $OPSMAN_NEW > $OPSMAN_CURRENT ]; then 
      echo "deleting old VM"
      az vm delete --name ${VM_NAME} \
      --resource-group ${RG_NAME} \
      --yes 
      echo "Starting update ofopsman from ${OPSMAN_CURRENT} to ${OPSMAN_NEW}"
      IMAGE_URI=https://${ACCOUNT_NAME}.blob.${SUFFIX_STORAGE_ENDPOINT}/${DESTINATION_CONTAINER}/${OPSMAN_VHD}
      # opsManVHD will be overwritten to the actual source
      az group create --name ${RESOURCE_GROUP} --location ${LOCATION}
      az group deployment create \
      --mode incremental \
      --resource-group ${RESOURCE_GROUP} \
      --parameters config/${PARAMETER_FILE} \
      --parameters ${ADDITIONAL_PARAMETERS} \
      --parameters opsManVHD=${OPSMAN_VHD} \
      --parameters OpsManImageURI=${IMAGE_URI} \
      --template-uri ${TEMPLATE_URI} \
      --parameter location=${LOCATION}
      generated_state_path="generated-state/$(basename "$STATE_FILE")"
      STATE=$(az vm show --name ${VM_NAME} \
        --resource-group ${RG_NAME} \
        --output json \
        --query '{VM_ID:name}')
        echo $STATE > ${generated_state_path} 
    else
      echo "Nothing to do for current opsman"
    fi  
    # echo $STATE | jq --arg iaas azurestack '. + {IAAS: $iaas}' > ${generated_state_path} 
    # ls -al
    # ls -al generated-state

